

## 4.PREPARING DATA

### 4.1 Preparing the data testing (preprocess con survived)

```{r}
preprocess <- function(data){
  
  data_model<- data
  
  data_model$PassengerId <- data$PassengerId
  
  if ("Survived" %in% names(data_model)) {
     data_model$Survived <- factor(data$Survived,
        levels = c(0, 1),
        labels = c("No", "Si"))
  }
  
  data_model$Pclass <- as.factor (data$Pclass)
  
  data_model$Surname <- sub(",.*", "", data$Name)
  
  data_model$Title <- sub("^.*,\\s*([^.]+)\\..*$", "\\1", data_model$Name)
  data_model$Title [ data_model$Title %in% c("Mlle", "Ms")] <- "Miss"
  data_model$Title [ data_model$Title %in% c("Mme")] <- "Mrs"
  data_model$Title [ data_model$Title %in% c("Dr","Rev","Col","Major","Capt",
  "Don", "Jonkheer", "Lady","Sir","the Countess", "Dona")] <- "Rare"
  
  data_model$Title <- as.factor(data_model$Title)
  data_model$Sex <- as.factor (data$Sex)
  
  data_model <- data_model %>%
    mutate(Age = case_when(
      is.na(Age) & (Title == "Master") & (Pclass == 1) ~ 1,
      is.na(Age) & (Title == "Master") & (Pclass == 2) ~ 2,
      is.na(Age) & (Title == "Master") & (Pclass == 3) ~ 5,
      is.na(Age) & (Title == "Miss") & (Pclass == 1) ~ 29,
      is.na(Age) & (Title == "Miss") & (Pclass == 2) ~ 23,
      is.na(Age) & (Title == "Miss") & (Pclass == 3) ~ 16,
      is.na(Age) & (Title == "Mr")   & (Pclass == 1) ~ 41,
      is.na(Age) & (Title == "Mr")   & (Pclass == 2) ~ 33,
      is.na(Age) & (Title == "Mr")   & (Pclass == 3) ~ 28,
      is.na(Age) & (Title == "Mrs")  & (Pclass == 1) ~ 40,
      is.na(Age) & (Title == "Mrs")  & (Pclass == 2) ~ 35,
      is.na(Age) & (Title == "Mrs")  & (Pclass == 3) ~ 33,
      is.na(Age) & (Title == "Rare") & (Pclass == 1) ~ 46,
      is.na(Age) & (Title == "Rare") & (Pclass == 2) ~ 41,
      TRUE ~ Age 
    ))
  
  data_model$SibSp <- data$SibSp
  data_model$Parch <- data$Parch
  
  data_model <- data_model %>%
    mutate(Fare = case_when(
      is.na(Fare) ~ 7.775, TRUE ~ Fare))
   
  data_model <- data_model %>%
    mutate(
      Embarked = if_else(Embarked == "", "S", Embarked)
  )

  data_model$Embarked <- as.factor(data_model$Embarked)
  
  data_model <- data_model %>% 
                dplyr::select(-Name, -Ticket, -Cabin,-Surname)

  return(data_model)
}
```


### 4.2 Preparing the data testing (preprocess2, sin survived) --NO SIRVE


```{r}
preprocess2 <- function(data){
  
  data_model<- data
  
  data_model$PassengerId <- data$PassengerId
  
  data_model$Pclass <- as.factor (data$Pclass)
  
  data_model$Surname <- sub(",.*", "", data$Name)
  
  data_model$Title <- sub("^.*,\\s*([^.]+)\\..*$", "\\1", data_model$Name)
  data_model$Title [ data_model$Title %in% c("Mlle", "Ms")] <- "Miss"
  data_model$Title [ data_model$Title %in% c("Mme")] <- "Mrs"
  data_model$Title [ data_model$Title %in% c("Dr","Rev","Col","Major","Capt",
  "Don", "Jonkheer", "Lady","Sir","the Countess", "Dona")] <- "Rare"
  
  data_model$Title <- as.factor(data_model$Title)
  
  data_model$Sex <- as.factor (data$Sex)
  
  data_model <- data_model %>%
    mutate(Age = case_when(
      is.na(Age) & (Title == "Master") & (Pclass == 1) ~ 1,
      is.na(Age) & (Title == "Master") & (Pclass == 2) ~ 2,
      is.na(Age) & (Title == "Master") & (Pclass == 3) ~ 5,
      is.na(Age) & (Title == "Miss") & (Pclass == 1) ~ 29,
      is.na(Age) & (Title == "Miss") & (Pclass == 2) ~ 23,
      is.na(Age) & (Title == "Miss") & (Pclass == 3) ~ 16,
      is.na(Age) & (Title == "Mr")   & (Pclass == 1) ~ 41,
      is.na(Age) & (Title == "Mr")   & (Pclass == 2) ~ 33,
      is.na(Age) & (Title == "Mr")   & (Pclass == 3) ~ 28,
      is.na(Age) & (Title == "Mrs")  & (Pclass == 1) ~ 40,
      is.na(Age) & (Title == "Mrs")  & (Pclass == 2) ~ 35,
      is.na(Age) & (Title == "Mrs")  & (Pclass == 3) ~ 33,
      is.na(Age) & (Title == "Rare") & (Pclass == 1) ~ 46,
      is.na(Age) & (Title == "Rare") & (Pclass == 2) ~ 41,
      TRUE ~ Age 
    ))
  
  data_model$SibSp <- data$SibSp
  data_model$Parch <- data$Parch
  
  data_model$Fare <- data$Fare
  
  
  data_model <- data_model %>%
    mutate(Fare = case_when(
      is.na(Fare) ~ 7.775, TRUE ~ Fare))
      
  data_model <- data_model %>%
    mutate(
      Embarked = if_else(Embarked == "", "S", Embarked)
  )
  
   data_model$Embarked <- as.factor(data_model$Embarked)

  data_model <- data_model %>% 
                dplyr::select(-Name, -Ticket, -Cabin,-Surname)

  return(data_model)
}
```


